_wandb:
    value:
        cli_version: 0.18.5
        m:
            - "1": global_step
              "6":
                - 3
              "7": []
            - "1": train/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
            "3":
                - 2
                - 7
                - 16
                - 23
                - 55
            "4": 3.11.8
            "5": 0.18.5
            "6": 4.46.1
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
N_layers:
    value: 2
batch_size:
    value: 48
d_model:
    value: 512
datasource:
    value: spanish-to-quechua
dropout:
    value: 0.1
experiment_name:
    value: runs/tmodel_qu_es
ffn_hidden:
    value: 2048
heads:
    value: 8
lang_src:
    value: qu
lang_tgt:
    value: es
lr:
    value: 0.0001
model_basename:
    value: tmodel_qu_es
model_folder:
    value: weights_qu_es
num_epochs:
    value: 30
preload:
    value: null
seq_len:
    value: 200
tokenizer_file:
    value: tokenizer_qu_es_{0}.json
