= Planteamiento del Problema
En el contexto del crecimiento de información y automatización de equipos mineros estos son cada vez mas complejos y con mayor sensorización lo que impacta en sus manuales, el volumen de información técnica disponible en las operaciones industriales ha crecido exponencialmente. En sectores críticos como la minería, y específicamente en las *plantas concentradoras de cobre*, la documentación técnica que incluye manuales de instalación, operación y mantenimiento (IOM), catálogos de partes, hojas de especificaciones, filosofías de control, arreglos generales y reportes de calidad constituye la base fundamental para la toma de decisiones en mantenimiento. Estos activos de información son vitales para garantizar la continuidad operativa; sin embargo, suelen presentarse en formatos heterogéneos y no estructurados (PDFs escaneados, imágenes, planos y diagramas), lo que dificulta su gestión y accesibilidad inmediata.\

Actualmente, la recuperación de información específica dentro de estos documentos presenta limitaciones significativas. Los técnicos, ingenieros y planificadores dependen de técnicas tradicionales como la lectura secuencial, el uso de índices estáticos (tablas de contenido), la búsqueda por palabras clave (_keyword search_) y búsqueda secuencial. Estos métodos resultan ineficientes ante la complejidad de los manuales modernos y antiguos, los cuales suelen caracterizarse por su gran extensión, terminología técnica ambigua y barreras idiomáticas. Más aún, existe una *desconexión semántica* en la búsqueda: la información crítica a menudo reside en formatos multimodales (como un plano de despiece o un diagrama de flujo) que los motores de búsqueda de texto tradicionales no pueden interpretar ni relacionar con las instrucciones escritas.\

Esta ineficiencia en la gestión del conocimiento impacta directamente en la gestión del mantenimiento. Una planificación efectiva requiere identificar con precisión el procedimiento de cambio, los repuestos exactos (ubicados en listas o planos de partes), las herramientas especiales y los tiempos estimados. La demora o el error en la localización de estos datos no solo consume horas-hombre valiosas de ingeniería, sino que incrementa el riesgo de errores en la ejecución ("mantenimiento incorrecto") o retrasos en la intervención. En una planta concentradora, donde la disponibilidad de los equipos es crítica, esta latencia en el acceso a la información puede traducirse en paradas de planta prolongadas y pérdidas significativas en la producción de cobre.

== Diagnóstico
En el área de planificación y mantenimiento de las plantas concentradoras de cobre, se observa una gestión documental dispersa y poco funcional. Actualmente, los manuales de equipos críticos y no críticos (como molinos de bolas, chancadoras, bombas y celdas de flotación) se almacenan en repositorios digitales masivos (Aconex, SharePoint, servidores locales) sin una indexación semántica adecuada, el almacenamiento actual esta basado en como se adquirieron en la etapa de proyecto y no por equipos, procesos o clase de equipo, flota o grupos de equipos (Ejemplo: Todas las bombas de la planta están agrupadas en una sola carpeta ya que todas las bombas de lodo fueron compradas a un mismo proveedor, caso similar con las celdas de flotación todas están en una sola carpeta y con un solo pdf por todos los tipos de celdas), esto impide realizar busqueda por proceso en la planta, o tag del equipo que se requiere información especifica.\

Se evidencia que, ante una falla o una parada programada, los planificadores/programadores de mantenimiento *invierten un tiempo excesivo navegando manualmente* entre carpetas y archivos PDF extensos algunos de los cuales son documentos escaneados ("imágenes de texto") lo que impide el uso de herramientas de búsqueda convencionales (Ctrl+F). Un síntoma recurrente es la dificultad para correlacionar la información visual con la textual; por ejemplo, el técnico encuentra el procedimiento de desmontaje en la página 50, pero el plano de despiece con los códigos de repuestos está en un anexo al final del documento o en un archivo separado, obligando a una validación manual cruzada propensa a errores. Además, la existencia de manuales en inglés técnico complejo genera barreras de comprensión inmediata por parte del personal operativo, retrasando la ejecución de las órdenes de trabajo.\

Se evidencia que los técnicos no realizan la búsqueda de especificaciones técnicas en manuales, generando que 6 de cada 10 condiciones de equipos reportados carezcan de información suficiente para la gestión de planificación del mantenimiento, especialmente en la identificación de los repuestos a cambiar.\


== Identificación y Diagnóstico del Problema de Estudio

El problema central identificado no es la inexistencia de información, sino la incapacidad de los sistemas de búsqueda actuales para procesar y relacionar información multimodal (texto e imagen) contenida en documentos técnicos no estructurados.\

Las técnicas de búsqueda tradicionales (basadas por palabras clave, lectura secuencial o búsqueda por tabla de contenidos) resultan insuficientes para interpretar consultas complejas de mantenimiento que requieren contexto, como "procedimiento de cambio de liner considerando el torque especificado en el plano A". Existe una brecha tecnológica entre la naturaleza heterogénea de los manuales IOM (que combinan diagramas, tablas de especificaciones y narrativas técnicas) y los mecanismos de recuperación de información disponibles, los cuales tratan el texto y la imagen como entidades desconectadas.\

Esta limitación tecnológica deriva en una baja precisión y retrabajo  en las consultas técnicas, lo que impacta negativamente en el tiempo medio de reparación (MTTR) y en la confiabilidad de la planificación de mantenimiento. Por lo tanto, el problema de estudio se define como la ineficiencia en la recuperación de información técnica contextualizada debido a la falta de integración semántica entre los datos textuales y visuales en los repositorios de mantenimiento de plantas mineras.\

=== Antecedentes bibliográficos

+ A nivel internacional, @nam_lora-tuned_2025 en su investigación titulada "LoRA-Tuned Multimodal RAG System for Technical Manual QA: A Case Study on Hyundai Staria", tuvieron como objetivo desarrollar un sistema RAG multimodal adaptable al dominio para mejorar la precisión en la respuesta a preguntas técnicas basadas en manuales estructurados a gran escala. La metodología consistió en extraer texto e imágenes de manuales PDF, construyendo datasets de QA y ajustando eficientemente los parámetros (fine-tuning) mediante LoRA (Low-Rank Adaptation) utilizando el modelo de lenguaje bLLossom-8B y el modelo de embedding BAAI-bge-m3. Los resultados mostraron mejoras significativas frente a sistemas RAG existentes: un aumento de 3.0 puntos porcentuales en BERTScore, 3.0 puntos en similitud coseno y un notable 18.0 puntos en ROUGE-L, destacando ganancias en respuestas guiadas por imágenes. Los autores concluyeron que el sistema ofrece una base robusta y escalable para QA multimodal en dominios especializados. Este trabajo es altamente relevante para la presente tesis, ya que demuestra cómo integrar diagramas técnicos y texto para resolver consultas de mantenimiento complejas, una necesidad crítica en la planificación industrial.

+ En el contexto de la producción industrial, @knollmeyer_document_2025 presentaron el estudio "Document GraphRAG: Knowledge Graph Enhanced Retrieval Augmented Generation for Document Question Answering Within the Manufacturing Domain". El objetivo fue abordar las limitaciones de precisión en la recuperación de los sistemas RAG tradicionales mediante la incorporación de Grafos de Conocimiento (KG) basados en la estructura intrínseca del documento. La metodología siguió el enfoque de Design Science Research (DSR), diseñando un sistema que utiliza una estructuración documental basada en grafos y un mecanismo de enlace semántico por palabras clave. Los resultados indicaron que GraphRAG superó consistentemente a una línea base de RAG ingenuo (naive RAG) tanto en métricas de recuperación como de generación, siendo particularmente superior en preguntas de múltiples saltos (multi-hop) que requieren razonamiento complejo. Se concluyó que la integración de KGs mejora la relevancia del contexto y que optimizaciones dependientes de la tarea (como el tamaño del chunk y la densidad de palabras clave) potencian el rendimiento. Este antecedente aporta una base metodológica sobre cómo estructurar documentación técnica dispersa para mejorar la toma de decisiones en planta.

+ Abordando la especificidad del lenguaje técnico, @knollmeyer_hybrid_2025 realizaron otra investigación titulada "Hybrid Retrieval for Retrieval Augmented Generation in the German Language Production Domain". Su objetivo fue evaluar el efecto de técnicas de recuperación híbrida en documentos técnicos de producción. La metodología propuso un enfoque híbrido combinando búsqueda de texto completo (Sparse) con búsqueda vectorial común (Dense), utilizando un corpus de documentos idénticos en inglés y alemán para la evaluación. Los resultados revelaron que el enfoque híbrido mejoró consistentemente el rendimiento de recuperación para documentos en alemán en un 20% sobre la búsqueda puramente vectorial, superando las deficiencias de los modelos de embedding en textos técnicos no ingleses. Los autores concluyeron que las estrategias de recuperación híbrida son esenciales para la gestión del conocimiento en contextos industriales técnicos. Este estudio es pertinente para justificar el uso de técnicas de recuperación híbrida (BM25 + Embeddings) en sistemas RAG aplicados a manuales de mantenimiento que contienen terminología técnica específica.

+ En el sector minero, @shu_utilizing_2024 desarrollaron la investigación "Utilizing Large Language Models for Hyper Knowledge Graph Construction in Mine Hoist Fault Analysis". El objetivo fue optimizar el proceso de construcción de grafos de conocimiento hiper-relacionales para fallas en polipastos de minas utilizando LLMs. La metodología integró la estructura topológica del grafo con reglas lógicas específicas del dominio, aplicando el algoritmo Variational EM para la optimización y predicción de enlaces. Los resultados mostraron que el modelo optimizado (MHSD) logró una mejora de 0.008 en la métrica MRR (Mean Reciprocal Rank) comparado con la versión no optimizada y superó al modelo KICGPT. Se concluyó que este enfoque permite la extracción automática y organización sistemática del conocimiento de fallas a partir de datos textuales no estructurados. Este trabajo aporta evidencia sobre cómo los LLMs pueden estructurar datos de mantenimiento predictivo y correctivo para el análisis de fallas.

+ Finalmente, @drushchak.etalMultimodalRetrievalAugmentedGenerationUnifiedInformationa propusieron en "Multimodal Retrieval-Augmented Generation: Unified Information Processing Across Text, Image, Table, and Video Modalities" un sistema unificado. El objetivo fue crear un pipeline capaz de procesar información a través de cuatro modalidades simultáneamente, superando las limitaciones de los sistemas RAG unimodales. La metodología utilizó herramientas como Amazon Textract y Transcribe junto con LLMs multimodales (Claude 3.5 Sonnet) para la ingesta e indexación de datos de PDFs y videos de manuales de servidores Dell. Los resultados mostraron una alta precisión en la recuperación de texto y tablas, aunque el rendimiento en video e imágenes fue menor pero prometedor . Los autores concluyeron que el marco de integración multimodal es robusto y subraya el valor de los pipelines unificados para datos diversos. Este estudio es clave para justificar la inclusión de videos y tablas complejas en un sistema de gestión del conocimiento para mantenimiento.

=== Formulación del Problema

==== Formulación del Problema General
¿Puede la implementación de un Sistema de Consultas Multimodal basada en Arquitectura Rag y fine tuning (LoRA) reducir el tiempo de busqueda de información técnica de manuales de de mantenimiento de equipos críticos de una planta concentradora de cobre?\

// ¿De qué manera la implementación de un Sistema de Consultas Multimodal basado en Arquitectura RAG (Retrieval-Augmented Generation) reduce el tiempo de busqueda de información técnica en los manuales de mantenimiento de plantas concentradoras de cobre, en comparación con los métodos de búsqueda tradicionales?

==== Formulación de los Problemas Específicos
+ ¿Cómo influye la integración semántica de datos multimodales (texto, planos, diagramas e imágenes) en la capacidad del sistema para responder consultas técnicas contextuales que requieren interpretación visual, a diferencia de la búsqueda puramente textual?

+ ¿Cuál es la mejora en la precisión y exhaustividad (recall) de la información recuperada al utilizar técnicas de embedding y re-ranking vectorial frente a la búsqueda léxica (palabras clave) en manuales con terminología heterogénea?

+ ¿En qué medida se reduce el tiempo de búsqueda de información crítica (procedimientos, especificaciones de repuestos y herramientas) para la planificación de mantenimiento al utilizar el asistente conversacional basado en RAG?

=== Justificación y Alcances
==== Justificación
La presenta investigación se justifica ante la creciente complejidad de la documentación técnica en entornos industriales y de ingeniería, donde la información crítica reside en manuales técnicos con información heterogénea (texto, imagenes, planos, etc.) esta información crítica escencial para toma de decisiones toma tiempo largo de extraer con metodos convencionales y los sistemas RAG(Retrieval-Augmented Generation) multimodales tienen la capacidad de entender y responder de forma rapida reduciendo esta brecha de tiempo entre la información y la toma de decisiones o acciones realies en la empresa industrial.
Desde una perspectiva técnica y operativa, el proyecto contribuye en el tiempo de busqueda de información lo cual genera un incremento positivo en el % wrench time del equipo de mantenimiento como lo describe @palmer_maintenance_2019 en su libro el wrench time(tiempo efectivo de mantenimiento) representa en el mejor de los casos del 55% del tiempo total disponible por el equipo técnico de mantenimiento, donde el 45% de tiempo restante corresponde a actividades de traslado, demoras entre sub procesos y *busqueda de información técnica* para ejecutar la actividad de mantenimiento, por lo que el proyecto va a contribuir en la eficiencia y utilización de las HHs del personal técnico de mantenimiento.
Desde una perspectiva economica la reducción de tiempo de busqueda de información va a ayudar en una rapida y mejor toma de decisiones lo cual contribuye en una respuesta mas rapida ante emergencias contribuyendo positivamente en la disponibilidad global de las plantas concentradora y con ello la producción asociada.

==== Alcances
El proyecto pretende generar un sistema RAG multimodal y Fine-Tuning (LoRa) para manuales de mantenimiento en planta concentradora con manuales facilitados por el stakeholder el cual pretende tener un anonimato y que la información tenga un estandar de confidencialidad, por lo que el stakeholder va a brindar los manuales que se requieren para este proyecto:  
 Limitaciones:
 - Solo se van a procesar PDF como tipo de información (ingesta de datos).
 - Base de conocimiento (corpus) es estricta a los manuales facilidados por el stakehokder.
 - El sistema no pretende generar nuevos diagramas, planos o imagenes.
 - Base de datos y sistemas va a ser proporsionada por el stakeholder solo en la etapa de producción, la etapa de prototipo se va a realizar un proceso interno de validación de financiamiento.

== Objetivo General
Desarrollar un Sistema de Consultas Multimodal basado en arquitectura RAG (Retrieval-Augmented Generation) para reducir el tiempo de busqueda de información técnica de los manuales de mantenimiento en plantas concentradoras de cobre.
== Objetivo Especifico

Estos objetivos representan los pasos técnicos y validaciones necesarias para alcanzar el objetivo general. Están alineados 1 a 1 con tus problemas específicos:

+ Diseñar e implementar un pipeline de procesamiento de datos multimodal que permita la extracción, vectorización e indexación conjunta de texto no estructurado y esquemas visuales (planos de partes, diagramas procedimientos, imágenes) contenidos en los manuales de mantenimiento.

+ Evaluar el desempeño del motor de recuperación mediante métricas de relevancia (Precision y Recall) BERTscore y ROUGE L(Recall Oriented Understudy for Gisting Evaluation).

+ Validar la utilidad del sistema en un entorno operativo, cuantificando la reducción del tiempo empleado por los planificadores en la búsqueda de información crítica y atención de reportes de condición.
